### ISSUE TITLE
Add John Burkardt's functions to test suite

### ISSUE THREAD

**Issue by Beliavsky** [libprima/prima#139]
For unconstrained optimization there are 43 functions in his [test_opt code](https://people.sc.fsu.edu/~jburkardt/f_src/test_opt/test_opt.html), there are 12 more in [test_optimization](https://people.sc.fsu.edu/~jburkardt/f_src/test_optimization/test_optimization.html), and there are 9 functions for constrained optimization in [test_opt_con](https://people.sc.fsu.edu/~jburkardt/f_src/test_opt_con/test_opt_con.html).

**Comment by zaikunzhang** [comment]
Hi @Beliavsky , thank you for your suggestions. I have had a look into the links. Most, if not all, of the problems are included in the CUTEst test suite. The problems therein are being tested extensively and intensively through the MATLAB interface via the MatCUTEst package. I intend to keep the Fortran tests simple, because it is much easily to test through MATLAB/Python/Julia/R interfaces.
